
name: Demo Node CI

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "main" ]
    types: 
       - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3       
    - name: Setup Nod Version
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Build Code
      run: npm install

  release-on-pullrequest:
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: github.event_name == 'pull_request'
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: "v"
          release_name: "Release 1.0.0"
          use_github_release_notes: true

  deploy-on-pr-merged-and-release:
    needs: release-on-pullrequest
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3       
      - name: Setup Nod Version
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build Code
        run: npm install
      - name: deploy to dev
        run: echo deploying code to dev
      
