
name: Demo Node CI

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup Nod Version
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Build Code
      run: npm install
 
