
name: Demo Node CI

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
    - name: Setup Nod Version
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Build Code
      run: npm install

  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: "v"
          release_name: "Release 1.0.0"
          use_github_release_notes: true
 
